# Generated by Django 4.2.2 on 2023-06-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default='1995-03-15'),
            preserve_default=False,
        ),
    ]
